<a href="https://colab.research.google.com/github/xmegan10/Reddit-Sentiment-Comment-Prediction/blob/main/Reddit%20Comment%20Sentiment%20Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install nltk
%pip install re
%pip install emoji
%pip install contractions
%pip install scikit-learn
%pip install collections
%pip install wordcloud
%pip install pyspark -v

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
ERROR: Could not find a version that satisfies the requirement re (from versions: none)
ERROR: No matching distribution found for re
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 22.6 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 14.6 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 12.8 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.1 textsearch-0.0.24
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (1.9.6)
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.12/dist-packages (from wordcloud) (2.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from wordcloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (26.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)
Using pip 24.1.2 from /usr/local/lib/python3.12/dist-packages/pip (python 3.12)
Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist
import re
import emoji #dealing with emojis
import contractions

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

from collections import Counter
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [3]:
import os
print(f"Current Working Directory: {os.getcwd()}")

Current Working Directory: /content

In [4]:
os.listdir()

['.config', 'sample_data']

In [5]:
import torch
torch.cuda.is_available()

True

In [6]:
from pyspark.sql import SparkSession, Row
spark = SparkSession.builder.appName('Load-jston-to-pyspark-dataframe').getOrCreate()
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
apr_comments = spark.read.json("/content/drive/MyDrive/Colab Notebooks/Reddit Comment Pred/r_AskReddit_commentsApril.jsonl")
apr_posts = spark.read.json("/content/drive/MyDrive/Colab Notebooks/Reddit Comment Pred/r_AskReddit_postsApril.jsonl")

In [9]:
apr_comments = apr_comments.select("*").toPandas()
apr_posts = apr_posts.select("*").toPandas()

# EDA

In [10]:
# head of data set
apr_posts.head()

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_cakeday,author_flair_background_color,author_flair_css_class,...,total_awards_received,treatment_tags,ups,upvote_ratio,url,user_reports,view_count,visited,websocket_url,wls
0,"{'edited_title': None, 'is_edited': None, 'rem...",[],False,None,None,False,534145,None,None,None,...,0,[],1,1.00,https://www.reddit.com/r/AskReddit/comments/1s...,[],None,False,None,6
1,"{'edited_title': None, 'is_edited': None, 'rem...",[],False,None,None,False,Only_Hotel_7221,None,None,None,...,0,[],100,0.88,https://www.reddit.com/r/AskReddit/comments/1s...,[],None,False,None,6
2,"{'edited_title': None, 'is_edited': None, 'rem...",[],False,None,None,False,jts_14,None,None,None,...,0,[],2,1.00,https://www.reddit.com/r/AskReddit/comments/1s...,[],None,False,wss://k8s-lb.wss.redditmedia.com/link/1s94k0r?...,6
3,"{'edited_title': None, 'is_edited': None, 'rem...",[],False,None,None,False,Captain_CrunchYaAss,None,None,None,...,0,[],3,1.00,https://www.reddit.com/r/AskReddit/comments/1s...,[],None,False,wss://k8s-lb.wss.redditmedia.com/link/1s94kun?...,6
4,"{'edited_title': None, 'is_edited': None, 'rem...",[],False,None,None,False,Agile_Wrangler_6731,None,None,None,...,0,[],48,0.94,https://www.reddit.com/r/AskReddit/comments/1s...,[],None,False,wss://k8s-lb.wss.redditmedia.com/link/1s94lab?...,6

In [11]:
apr_posts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33200 entries, 0 to 33199
Columns: 109 entries, _meta to wls
dtypes: bool(28), float64(1), int64(13), object(67)
memory usage: 21.4+ MB

In [12]:
apr_posts.columns.tolist()

['_meta',
 'all_awardings',
 'allow_live_comments',
 'approved_at_utc',
 'approved_by',
 'archived',
 'author',
 'author_cakeday',
 'author_flair_background_color',
 'author_flair_css_class',
 'author_flair_richtext',
 'author_flair_template_id',
 'author_flair_text',
 'author_flair_text_color',
 'author_flair_type',
 'author_fullname',
 'author_is_blocked',
 'author_patreon_flair',
 'author_premium',
 'awarders',
 'banned_at_utc',
 'banned_by',
 'can_gild',
 'can_mod_post',
 'category',
 'clicked',
 'content_categories',
 'contest_mode',
 'created',
 'created_utc',
 'discussion_type',
 'distinguished',
 'domain',
 'downs',
 'edited',
 'gilded',
 'hidden',
 'hide_score',
 'id',
 'is_created_from_ads_ui',
 'is_crosspostable',
 'is_meta',
 'is_original_content',
 'is_reddit_media_domain',
 'is_robot_indexable',
 'is_self',
 'is_video',
 'likes',
 'link_flair_background_color',
 'link_flair_css_class',
 'link_flair_richtext',
 'link_flair_template_id',
 'link_flair_text',
 'link_flair_text_color',
 'link_flair_type',
 'location_lat',
 'location_long',
 'location_name',
 'locked',
 'media',
 'media_only',
 'mod_note',
 'mod_reason_by',
 'mod_reason_title',
 'mod_reports',
 'name',
 'no_follow',
 'num_comments',
 'num_crossposts',
 'num_reports',
 'over_18',
 'permalink',
 'pinned',
 'poll_data',
 'pwls',
 'quarantine',
 'removal_reason',
 'removed_by',
 'removed_by_category',
 'report_reasons',
 'retrieved_on',
 'saved',
 'score',
 'secure_media',
 'selftext',
 'send_replies',
 'spoiler',
 'stickied',
 'subreddit',
 'subreddit_id',
 'subreddit_name_prefixed',
 'subreddit_subscribers',
 'subreddit_type',
 'suggested_sort',
 'thumbnail',
 'thumbnail_height',
 'thumbnail_width',
 'title',
 'top_awarded_type',
 'total_awards_received',
 'treatment_tags',
 'ups',
 'upvote_ratio',
 'url',
 'user_reports',
 'view_count',
 'visited',
 'websocket_url',
 'wls']

In [13]:
apr_comments.head()

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_cakeday,author_flair_background_color,author_flair_css_class,...,subreddit,subreddit_id,subreddit_name_prefixed,subreddit_type,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,ups,user_reports
0,"{'is_edited': None, 'removal_type': None, 'ret...",[],None,None,False,None,QuayleDan128,None,None,None,...,AskReddit,t5_2qh1i,r/AskReddit,public,None,0,[],None,1,[]
1,"{'is_edited': None, 'removal_type': None, 'ret...",[],None,None,False,None,_persian_princess_,None,None,None,...,AskReddit,t5_2qh1i,r/AskReddit,public,None,0,[],None,3,[]
2,"{'is_edited': None, 'removal_type': None, 'ret...",[],None,None,False,None,anormalgeek,None,None,None,...,AskReddit,t5_2qh1i,r/AskReddit,public,None,0,[],None,4,[]
3,"{'is_edited': None, 'removal_type': None, 'ret...",[],None,None,False,None,skatefan420,None,None,None,...,AskReddit,t5_2qh1i,r/AskReddit,public,None,0,[],None,2,[]
4,"{'is_edited': None, 'removal_type': None, 'ret...",[],None,None,False,None,ThinkIndependently5,None,None,None,...,AskReddit,t5_2qh1i,r/AskReddit,public,None,0,[],None,1,[]

In [14]:
apr_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 833548 entries, 0 to 833547
Data columns (total 73 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   _meta                            810063 non-null  object
 1   all_awardings                    833548 non-null  object
 2   approved_at_utc                  0 non-null       object
 3   approved_by                      0 non-null       object
 4   archived                         833548 non-null  bool
 5   associated_award                 0 non-null       object
 6   author                           833548 non-null  object
 7   author_cakeday                   2567 non-null    object
 8   author_flair_background_color    23900 non-null   object
 9   author_flair_css_class           0 non-null       object
 10  author_flair_richtext            809899 non-null  object
 11  author_flair_template_id         0 non-null       object
 12  author_flair_text                0 non-null       object
 13  author_flair_text_color          23900 non-null   object
 14  author_flair_type                809899 non-null  object
 15  author_fullname                  809648 non-null  object
 16  author_is_blocked                833548 non-null  bool
 17  author_patreon_flair             809899 non-null  object
 18  author_premium                   809899 non-null  object
 19  awarders                         833548 non-null  object
 20  banned_at_utc                    0 non-null       object
 21  banned_by                        0 non-null       object
 22  body                             833548 non-null  object
 23  can_gild                         833548 non-null  bool
 24  can_mod_post                     833548 non-null  bool
 25  collapsed                        833548 non-null  bool
 26  collapsed_because_crowd_control  0 non-null       object
 27  collapsed_reason                 314 non-null     object
 28  collapsed_reason_code            24118 non-null   object
 29  comment_type                     0 non-null       object
 30  controversiality                 833548 non-null  int64
 31  created                          833548 non-null  int64
 32  created_utc                      833548 non-null  int64
 33  distinguished                    4897 non-null    object
 34  downs                            833548 non-null  int64
 35  editable                         1189 non-null    object
 36  edited                           833548 non-null  object
 37  gilded                           833548 non-null  int64
 38  id                               833548 non-null  object
 39  is_submitter                     833548 non-null  bool
 40  likes                            0 non-null       object
 41  link_id                          833548 non-null  object
 42  locked                           833548 non-null  bool
 43  mod_note                         0 non-null       object
 44  mod_reason_by                    0 non-null       object
 45  mod_reason_title                 0 non-null       object
 46  mod_reports                      833548 non-null  object
 47  name                             833548 non-null  object
 48  no_follow                        833548 non-null  bool
 49  num_reports                      0 non-null       object
 50  parent_id                        833548 non-null  object
 51  permalink                        833548 non-null  object
 52  profile_img                      809795 non-null  object
 53  profile_over_18                  809795 non-null  object
 54  removal_reason                   176 non-null     object
 55  replies                          833548 non-null  object
 56  report_reasons                   0 non-null       object
 57  retrieved_on                     833548 non-null  int64
 58  saved                            833548 non-null  bool
 59  score                            833548 non-null  int64
 60  score_hidden                     833548 non-null  bool
 61  send_replies                     833548 non-null  bool
 62  stickied                         833548 non-null  bool
 63  subreddit                        833548 non-null  object
 64  subreddit_id                     833548 non-null  object
 65  subreddit_name_prefixed          833548 non-null  object
 66  subreddit_type                   833548 non-null  object
 67  top_awarded_type                 0 non-null       object
 68  total_awards_received            833548 non-null  int64
 69  treatment_tags                   833548 non-null  object
 70  unrepliable_reason               0 non-null       object
 71  ups                              833548 non-null  int64
 72  user_reports                     833548 non-null  object
dtypes: bool(12), int64(9), object(52)
memory usage: 397.5+ MB

In [15]:
def create_edadf(*dataframes):
    eda_df = []
    for df in dataframes:
        eda_df.append({
            "name": df.name,
            "num_rows": df.shape[0],
            "num_cols": df.shape[1],
            "contains_null": df.isnull().any(axis = None)
        })
    return pd.DataFrame(eda_df)

p_eda_df = create_edadf(apr_posts)
c_eda_df = create_edadf(apr_comments)

In [17]:
p_eda_df

,name,num_rows,num_cols,contains_null
0,0 t3_1s94jjw 1 t3_1s94jno 2 ...,33200,109,True

In [18]:
c_eda_df

,name,num_rows,num_cols,contains_null
0,0 t1_odlodpk 1 t1_odlodp9 2 ...,833548,73,True

In [16]:
posts_df = apr_posts.copy()
comments_df = apr_comments.copy()

# Split Data into Train and Test

In [17]:
#remove t3 from link_id in comments_df
comments_df['link_id'] = comments_df['link_id'].str.replace('t3_', '')
comments_df['link_id'].value_counts()

link_id
1sa3jwv    13149
1sdmusm     9136
1scriio     8994
1sbcji8     8162
1sagz0b     7931
           ...
1sass35        1
1sasscy        1
1sase9e        1
1saseb4        1
1sasgbw        1
Name: count, Length: 33591, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
ptrain_set, ptest_set = train_test_split(posts_df, test_size = 0.2, random_state = 42)

#get the list of IDs for each split
ptrain_ids = ptrain_set['id'].unique()
ptest_ids = ptest_set['id'].unique()

ctrain_set = comments_df[comments_df['link_id'].isin(ptrain_ids)]
ctest_set = comments_df[comments_df['link_id'].isin(ptest_ids)]

In [19]:
ptrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26560 entries, 18578 to 15795
Columns: 109 entries, _meta to wls
dtypes: bool(28), float64(1), int64(13), object(67)
memory usage: 17.3+ MB

In [23]:
ctrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644213 entries, 96 to 833545
Data columns (total 73 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   _meta                            628259 non-null  object
 1   all_awardings                    644213 non-null  object
 2   approved_at_utc                  0 non-null       object
 3   approved_by                      0 non-null       object
 4   archived                         644213 non-null  bool
 5   associated_award                 0 non-null       object
 6   author                           644213 non-null  object
 7   author_cakeday                   1993 non-null    object
 8   author_flair_background_color    18005 non-null   object
 9   author_flair_css_class           0 non-null       object
 10  author_flair_richtext            626401 non-null  object
 11  author_flair_template_id         0 non-null       object
 12  author_flair_text                0 non-null       object
 13  author_flair_text_color          18005 non-null   object
 14  author_flair_type                626401 non-null  object
 15  author_fullname                  626208 non-null  object
 16  author_is_blocked                644213 non-null  bool
 17  author_patreon_flair             626401 non-null  object
 18  author_premium                   626401 non-null  object
 19  awarders                         644213 non-null  object
 20  banned_at_utc                    0 non-null       object
 21  banned_by                        0 non-null       object
 22  body                             644213 non-null  object
 23  can_gild                         644213 non-null  bool
 24  can_mod_post                     644213 non-null  bool
 25  collapsed                        644213 non-null  bool
 26  collapsed_because_crowd_control  0 non-null       object
 27  collapsed_reason                 213 non-null     object
 28  collapsed_reason_code            18146 non-null   object
 29  comment_type                     0 non-null       object
 30  controversiality                 644213 non-null  int64
 31  created                          644213 non-null  int64
 32  created_utc                      644213 non-null  int64
 33  distinguished                    3917 non-null    object
 34  downs                            644213 non-null  int64
 35  editable                         783 non-null     object
 36  edited                           644213 non-null  object
 37  gilded                           644213 non-null  int64
 38  id                               644213 non-null  object
 39  is_submitter                     644213 non-null  bool
 40  likes                            0 non-null       object
 41  link_id                          644213 non-null  object
 42  locked                           644213 non-null  bool
 43  mod_note                         0 non-null       object
 44  mod_reason_by                    0 non-null       object
 45  mod_reason_title                 0 non-null       object
 46  mod_reports                      644213 non-null  object
 47  name                             644213 non-null  object
 48  no_follow                        644213 non-null  bool
 49  num_reports                      0 non-null       object
 50  parent_id                        644213 non-null  object
 51  permalink                        644213 non-null  object
 52  profile_img                      626314 non-null  object
 53  profile_over_18                  626314 non-null  object
 54  removal_reason                   111 non-null     object
 55  replies                          644213 non-null  object
 56  report_reasons                   0 non-null       object
 57  retrieved_on                     644213 non-null  int64
 58  saved                            644213 non-null  bool
 59  score                            644213 non-null  int64
 60  score_hidden                     644213 non-null  bool
 61  send_replies                     644213 non-null  bool
 62  stickied                         644213 non-null  bool
 63  subreddit                        644213 non-null  object
 64  subreddit_id                     644213 non-null  object
 65  subreddit_name_prefixed          644213 non-null  object
 66  subreddit_type                   644213 non-null  object
 67  top_awarded_type                 0 non-null       object
 68  total_awards_received            644213 non-null  int64
 69  treatment_tags                   644213 non-null  object
 70  unrepliable_reason               0 non-null       object
 71  ups                              644213 non-null  int64
 72  user_reports                     644213 non-null  object
dtypes: bool(12), int64(9), object(52)
memory usage: 312.1+ MB

In [20]:
missing_ids = ctrain_set[~ctrain_set['link_id'].isin(ptrain_set['id'])]['id'].unique()

print(f"Number of unique Post IDs missing from ptrain_setk: {len(missing_ids)}")
print("First 10 missing IDs:", missing_ids[:10])

Number of unique Post IDs missing from ptrain_setk: 0
First 10 missing IDs: []

# Remove Null and One-Unique-only columns

In [21]:
len(ctrain_set.index)

644213

In [22]:
def drop_cols(df):
  for c in df.columns:
    # Check if all values are null
    if df[c].isnull().sum() == len(df.index):
      df.drop(c, axis=1, inplace=True)
    else:
      # Try to check for unique values. If TypeError occurs,
      # convert elements to string representation
      try:
        if len(df[c].unique()) == 1:
          df.drop(c, axis=1, inplace=True)
      except TypeError:
        # Handle unhashable types
        # Convert to string to check if all string representations are the same
        if df[c].astype(str).nunique() == 1:
          df.drop(c, axis=1, inplace=True)
  return df

In [23]:
ptrain_set = drop_cols(ptrain_set)
ctrain_set = drop_cols(ctrain_set)

/tmp/ipykernel_692/2402450421.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)
/tmp/ipykernel_692/2402450421.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(c, axis=1, inplace=True)

In [24]:
ptrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26560 entries, 18578 to 15795
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _meta                          25637 non-null  object
 1   author                         26560 non-null  object
 2   author_cakeday                 71 non-null     object
 3   author_flair_background_color  1572 non-null   object
 4   author_flair_richtext          24988 non-null  object
 5   author_flair_text_color        1572 non-null   object
 6   author_flair_type              24988 non-null  object
 7   author_fullname                24988 non-null  object
 8   author_patreon_flair           24988 non-null  object
 9   author_premium                 24988 non-null  object
 10  created                        26560 non-null  int64
 11  created_utc                    26560 non-null  int64
 12  domain                         26560 non-null  object
 13  edited                         26560 non-null  object
 14  id                             26560 non-null  object
 15  is_crosspostable               26560 non-null  bool
 16  is_robot_indexable             26560 non-null  bool
 17  link_flair_background_color    26560 non-null  object
 18  link_flair_richtext            26560 non-null  object
 19  link_flair_template_id         95 non-null     object
 20  link_flair_text                95 non-null     object
 21  link_flair_text_color          26560 non-null  object
 22  link_flair_type                26560 non-null  object
 23  locked                         26560 non-null  bool
 24  name                           26560 non-null  object
 25  no_follow                      26560 non-null  bool
 26  num_comments                   26560 non-null  int64
 27  num_crossposts                 26560 non-null  int64
 28  over_18                        26560 non-null  bool
 29  permalink                      26560 non-null  object
 30  poll_data                      1253 non-null   object
 31  removal_reason                 24 non-null     object
 32  removed_by_category            7209 non-null   object
 33  retrieved_on                   26560 non-null  int64
 34  score                          26560 non-null  int64
 35  selftext                       26560 non-null  object
 36  send_replies                   26560 non-null  bool
 37  spoiler                        26560 non-null  bool
 38  subreddit_subscribers          26560 non-null  int64
 39  thumbnail                      26454 non-null  object
 40  title                          26560 non-null  object
 41  ups                            26560 non-null  int64
 42  upvote_ratio                   26560 non-null  float64
 43  url                            26560 non-null  object
 44  websocket_url                  15954 non-null  object
dtypes: bool(7), float64(1), int64(8), object(29)
memory usage: 8.1+ MB

In [29]:
ctrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644213 entries, 96 to 833545
Data columns (total 37 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   _meta                          628259 non-null  object
 1   author                         644213 non-null  object
 2   author_cakeday                 1993 non-null    object
 3   author_flair_background_color  18005 non-null   object
 4   author_flair_richtext          626401 non-null  object
 5   author_flair_text_color        18005 non-null   object
 6   author_flair_type              626401 non-null  object
 7   author_fullname                626208 non-null  object
 8   author_patreon_flair           626401 non-null  object
 9   author_premium                 626401 non-null  object
 10  body                           644213 non-null  object
 11  collapsed                      644213 non-null  bool
 12  collapsed_reason               213 non-null     object
 13  collapsed_reason_code          18146 non-null   object
 14  controversiality               644213 non-null  int64
 15  created                        644213 non-null  int64
 16  created_utc                    644213 non-null  int64
 17  distinguished                  3917 non-null    object
 18  editable                       783 non-null     object
 19  edited                         644213 non-null  object
 20  id                             644213 non-null  object
 21  is_submitter                   644213 non-null  bool
 22  link_id                        644213 non-null  object
 23  locked                         644213 non-null  bool
 24  name                           644213 non-null  object
 25  no_follow                      644213 non-null  bool
 26  parent_id                      644213 non-null  object
 27  permalink                      644213 non-null  object
 28  profile_img                    626314 non-null  object
 29  profile_over_18                626314 non-null  object
 30  removal_reason                 111 non-null     object
 31  retrieved_on                   644213 non-null  int64
 32  score                          644213 non-null  int64
 33  score_hidden                   644213 non-null  bool
 34  send_replies                   644213 non-null  bool
 35  stickied                       644213 non-null  bool
 36  ups                            644213 non-null  int64
dtypes: bool(7), int64(6), object(24)
memory usage: 156.7+ MB

# Select only relevant columns

In [25]:
ptrain_keep_cols = ["created_utc",
                    "id",
                    "is_crosspostable",
                    "link_flair_text",
                    "link_flair_type",
                    "over_18",
                    "poll_data",
                    "selftext",
                    "spoiler",
                    "thumbnail",
                    "title"]

ctrain_keep_cols = ["body",
                    "created_utc",
                    "distinguished",
                    "id",
                    "link_id",
                    "locked",
                    "parent_id",
                    "score",
                    "stickied",
                    "ups"]

In [26]:
ptrain_set = ptrain_set[ptrain_keep_cols]
ctrain_set = ctrain_set[ctrain_keep_cols]

In [27]:
ptrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26560 entries, 18578 to 15795
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   created_utc       26560 non-null  int64
 1   id                26560 non-null  object
 2   is_crosspostable  26560 non-null  bool
 3   link_flair_text   95 non-null     object
 4   link_flair_type   26560 non-null  object
 5   over_18           26560 non-null  bool
 6   poll_data         1253 non-null   object
 7   selftext          26560 non-null  object
 8   spoiler           26560 non-null  bool
 9   thumbnail         26454 non-null  object
 10  title             26560 non-null  object
dtypes: bool(3), int64(1), object(7)
memory usage: 1.9+ MB

In [33]:
ctrain_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644213 entries, 96 to 833545
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   body           644213 non-null  object
 1   created_utc    644213 non-null  int64
 2   distinguished  3917 non-null    object
 3   id             644213 non-null  object
 4   link_id        644213 non-null  object
 5   locked         644213 non-null  bool
 6   parent_id      644213 non-null  object
 7   score          644213 non-null  int64
 8   stickied       644213 non-null  bool
 9   ups            644213 non-null  int64
dtypes: bool(2), int64(3), object(5)
memory usage: 45.5+ MB

# Preprocess Text

In [28]:
ptrain_set[ptrain_set["selftext"] != ""]["selftext"].value_counts()

selftext
[removed]                                                                                   1115
[deleted]                                                                                    435
[ Removed by Reddit on account of violating the [content policy](/help/contentpolicy). ]       7
Name: count, dtype: int64

In [31]:
#group removed and rename all types
ptrain_set["selftext"] = ptrain_set["selftext"].replace({"":'none','[removed]':'removed','[ Removed by Reddit on account of violating the [content policy](/help/contentpolicy). ]':'removed','[deleted]':'deleted'})

In [33]:
#rename selftext column to status
ptrain_set = ptrain_set.rename(columns = {"selftext":"status"})

In [34]:
ptrain_set["status"].value_counts()

status
none       25003
removed     1122
deleted      435
Name: count, dtype: int64

In [ ]:
#r/AskReddit does not frequently has posts with bodies, so we skip this code for now. In the future if using this code on a subreddit with long bodies, you can use this code:
#combines selftext (body) with title (post title)

#ptrain_set["post_string"] = ptrain_set["post_title"].str.cat(ptrain_set["post_text"], sep = " ",na_rep = "")
#ptrain_set["post_string"].eq("").sum()

In [ ]:
#add meta data to improve training
#add word counts of post_string as pstring_len
ptrain_set["post_length"] = ptrain_set["post_string"].str.split().str.len()
ptrain_set.head()

In [ ]:
def preprocess_df(df, text_col = "post_string"):
    #CLEAN TEXT
    processed_texts = []

    #loading stop words and objects from classes
    default_stopwords = set(stopwords.words('english'))
    default_stopwords.add("edit")
    lmtzr = WordNetLemmatizer()

    def clean_text(sentence):
        #return "" if sentence is NaN so no error occurs
        if not isinstance(sentence, str) or sentence.strip() == "":
            return ""

        #convert emojis to text
        sentence = emoji.demojize(sentence)
        #remove https from strings
        sentence = re.sub(r'http\S+','', sentence)
        #remove new lines
        sentence = re.sub(r'\\n|:|_',' ', sentence)
        #expand contractions
        sentence = contractions.fix(sentence)
        #remove punctuations and lowercase
        sentence = re.sub(r'[^a-zA-Z0-9\s]', '', sentence).lower()


        #tokenize words
        tokens = word_tokenize(sentence)

        final_words = []
        for word in tokens: #for each word in the sentence
            fixed_word = contractions.fix(word) #expand contractions
            if fixed_word not in default_stopwords:
                lemma = lmtzr.lemmatize(fixed_word) #lemmatize words
                final_words.append(lemma) #append the singular lemmatized word to the final_words list

        return ' '.join(final_words) #append the list of words to processed_text

    df[text_col] = df[text_col].apply(clean_text)
    return df

In [ ]:
ptrain_set = preprocess_df(ptrain_set, text_col = "post_string")

In [ ]:
ptrain_set["post_string"]

In [ ]:
ptrain_set_test = ptrain_set.copy()

## Pipeline: FeaturePreprocessor

In [ ]:
#write pipeline for preprocess step
from sklearn.base import BaseEstimator, TransformerMixin

class FeaturePreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self, variables = None):
        self.variables = variables #placeholder for now; change if need to add specific conditions

        self.stop_words = set(stopwords.words('english'))
        self.stop_words.add("edit")
        self.lmtzr = WordNetLemmatizer()

    def fit(self, X, y = None):
        return self

    def clean_text(self, text):
        if not isinstance(text, str) or text.strip() == "":
            return ""

        #convert emojis to text
        text = emoji.demojize(text)
        #expand contractions
        text = contractions.fix(text)
        #remove https from strings
        text = re.sub(r'http\S+','', text)
        #remove new lines
        text = re.sub(r'\\n|:|_',' ', text)
        #remove punctuations and lowercase
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text).lower()

        #tokenize words
        tokens = word_tokenize(text)
        cleaned_tokens = [self.lmtzr.lemmatize(word) for word in tokens if word not in self.stop_words]

        return cleaned_tokens


    def transform(self, X):
        X = X.copy()

        #combine post_title and post_text into post_string
        X["post_string"] = X["post_title"].str.cat(X["post_text"], sep = " ",na_rep = "")
        #add word counts of post_string as pstring_len
        X["pstring_len"] = X["post_string"].str.split().str.len()

        X["post_string"] = X["post_string"].apply(self.clean_text).str.join(" ")

        return X

In [ ]:
feat_preprocessor = FeaturePreprocessor()
ptrain_set_test = feat_preprocessor.transform(ptrain_set_test)